FROM debian:bullseye

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install --yes \
        build-essential \
        debhelper \
        git \
        meson \
        libglib2.0-dev \
        libyaml-dev \
        libparted-dev && \
    rm -rf /var/lib/apt/lists/*
