name: unit-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted-v2, self-hosted-ubuntu-22.04-v2]
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install meson libglib2.0-dev libyaml-dev libparted-dev
      - name: Build unit tests and program
        run: meson setup build --buildtype=debug
      - name: Run user unit tests
        run: meson test --suite user -C build --print-errorlogs --verbose
      - name: Run root unit tests
        run: sudo meson test --suite root -C build --print-errorlogs --verbose
